Repository MafiaHub/Framework, pull requests merged in 2025-04, with the labels that each got.

#144 Client side scripting
  code/framework/CMakeLists.txt
  code/framework/src/core_modules.h
  code/framework/src/gui/backend/view_d3d11.cpp
  code/framework/src/gui/backend/view_d3d11.h
  code/framework/src/gui/manager.cpp
  code/framework/src/gui/manager.h
  code/framework/src/gui/view.cpp
  code/framework/src/gui/view.h
  code/framework/src/integrations/client/instance.cpp
  code/framework/src/integrations/client/instance.h
  code/framework/src/integrations/client/scripting/builtins/events_lua.h
  code/framework/src/integrations/client/scripting/module.cpp
  code/framework/src/integrations/client/scripting/module.h
  code/framework/src/integrations/server/instance.cpp
  code/framework/src/integrations/server/instance.h
  code/framework/src/integrations/server/scripting/builtins/entity.h
  code/framework/src/integrations/server/scripting/builtins/events_lua.h
  code/framework/src/integrations/server/scripting/module.cpp
  code/framework/src/integrations/server/scripting/module.h
  code/framework/src/integrations/server/scripting/server.cpp
  code/framework/src/integrations/server/scripting/server.h
  code/framework/src/integrations/shared/rpc/emit_lua_event.h
  code/framework/src/scripting/builtins/color_rgb.h
  code/framework/src/scripting/builtins/color_rgba.h
  code/framework/src/scripting/builtins/console.h
  code/framework/src/scripting/builtins/event.h
  code/framework/src/scripting/builtins/json.h
  code/framework/src/scripting/builtins/quaternion.h
  code/framework/src/scripting/builtins/vector_2.h
  code/framework/src/scripting/builtins/vector_3.h
  code/framework/src/scripting/client_engine.cpp
  code/framework/src/scripting/client_engine.h
  code/framework/src/scripting/engine.cpp
  code/framework/src/scripting/engine.h
  code/framework/src/scripting/module.cpp
  code/framework/src/scripting/module.h
  code/framework/src/scripting/server_engine.cpp
  code/framework/src/scripting/server_engine.h
  code/framework/src/scripting/shared.h
  code/framework/src/scripting/types/errors.h
  code/framework/src/scripting/utils/table_conversions.h
  code/framework/src/utils/path.cpp
  code/framework/src/utils/path.h
  code/framework/src/world/engine.h
  code/tests/modules/scripting_module_ut.h
Labels: enhancement

#152 wip: webview sdk
  code/framework/src/core_modules.h
  code/framework/src/gui/manager.cpp
  code/framework/src/gui/manager.h
  code/framework/src/gui/view.h
  code/framework/src/integrations/client/instance.cpp
  code/framework/src/integrations/client/instance.h
  code/framework/src/integrations/client/scripting/builtins/views.h
  code/framework/src/integrations/server/scripting/module.cpp
  code/framework/src/integrations/shared/rpc/reload_assets.h
Labels: enhancement, priority:high

#153 webview events
  code/framework/src/gui/sdk.h
  code/framework/src/gui/view.h
  code/framework/src/integrations/client/scripting/builtins/views.h
Labels: enhancement, priority:low

#146 RGB/RGBA as integer
  code/framework/src/scripting/builtins/color_rgb.h
  code/framework/src/scripting/builtins/color_rgba.h
Labels: enhancement

#157 add: input sdk
  code/framework/src/core_modules.h
  code/framework/src/gui/backend/view_d3d11.cpp
  code/framework/src/gui/backend/view_d3d11.h
  code/framework/src/gui/manager.cpp
  code/framework/src/gui/manager.h
  code/framework/src/gui/view.cpp
  code/framework/src/gui/view.h
  code/framework/src/input/input.h
  code/framework/src/integrations/client/instance.cpp
  code/framework/src/integrations/client/instance.h
  code/framework/src/integrations/client/scripting/builtins/input.h
  code/framework/src/integrations/client/scripting/builtins/views.h
Labels: enhancement
